package ejercicio21;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-08-18T18:34:05.074-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://ejercicio21/", name = "IEncriptarPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IEncriptarPortType {

    @WebMethod
    @RequestWrapper(localName = "encriptar", targetNamespace = "http://ejercicio21/", className = "ejercicio21.Encriptar")
    @ResponseWrapper(localName = "encriptarResponse", targetNamespace = "http://ejercicio21/", className = "ejercicio21.EncriptarResponse")
    @WebResult(name = "return", targetNamespace = "http://ejercicio21/")
    public java.lang.String encriptar(
        @WebParam(name = "arg0", targetNamespace = "http://ejercicio21/")
        java.lang.String arg0
    );
}
